### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "joao.silva@example.com",
    "password": "password123"
}

### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "fariaa@hotmail.com",
    "password": "teste@123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "fariaa@hotmail.com",
    "password": "teste@123"
}

### Salvar o token da resposta
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhcmlhYUBob3RtYWlsLmNvbSIsInN1YiI6InVzZXJfenZWMzBPWWtvR2xYeG5nZFl3emRDIiwiaWF0IjoxNzQxNzQ2MjY3LCJleHAiOjE3NDE3NDk4Njd9.YeabwQME5-G1sBkPmHcNBCExgXK7McfHwnTXi3Hvj4c

### create author
POST http://localhost:3000/authors
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "João Silva",
  "email": "teste.silva@example.com",
  "bio": "João Silva é um escritor apaixonado por tecnologia e programação.",
  "profilePicture": "https://exemplo.com/foto-perfil.jpg"
}